properties:
    asset: None
    dcc:
        asset_root: master
        geometry_hi_root: hi
        hair_root: hair
        effect_root: effect

option:
    indent: 4
    linesep: "\n"

usd:
    presets:
        up_axis: Y
        linear_unit: 0.01

    layers:
        surface: {}
        effect: {}
        hair: {}
        model: {}
