menu:
    label: TD-tool(s)
    tools:
        - scene_packager
        - separator
        - package_reloader
tool:
    package_reloader:
        chn_label: None
        command: ''
        icon: None
        label: Package-reloader
        size:
            - 720
            - 560
    scene_packager:
        chn_label: None
        command: ''
        icon: None
        label: Scene-packager
        size:
            - 1280
            - 720
