windows:
    'L:':
        - '/l'
    'O:':
        - '/o'
    'Q:':
        - '/depts'
linux:
    '/l':
        - 'L:'
        - 'l:'
    '/o':
        - 'O:'
        - 'o:'
    '/depts':
        - 'Q:'
        - 'q:'