menu:
    label: TD-tool(s)
    tools:
        - shot_builder
# tool
tool:
    shot_builder:
        chn_label: None
        command: ''
        icon: None
        label: Shot-builder
        size:
            - 1280
            - 720
