# storage-configure for cg-project
# ******************************************************************************************************************** #
# pattern-rule:
#     keyword: str(pattern)
#     if <keyword> in value auto resolve to final value
# ******************************************************************************************************************** #
key: new
key_extras: [ 'nsa_dev', 'tnt' ]
#
variant-fnmatch-patterns:
    role: '[a-z][a-z][a-z]'
    sequence: '[a-z]*'
    step: '[a-z]*'
    version: '[a-z][0-9][0-9][0-9]'
    version_extra: '[0-9][0-9][0-9]'
    look_pass: '[A-Za-z]*'
    shot: '{sequence}*'
#
root-step-choice:
    source: {}
    release: {}
    temporary: {}
# <root>
project-root-windows-dir: 'z:/shows'
project-root-linux-dir: '/production/shows'
#
project-root_primary-windows-dir: 'z:/shows'
project-root_primary-linux-dir: '/production/shows'
#
project-root_secondary-windows-dir: 't:/prod'
project-root_secondary-linux-dir: '/t/prod'
# workspaces
workspaces:
    source: team
    user: work
    release: shared
    temporary: cache
# asset steps
asset_steps:
    concept: cpt
    paint: pnt
    #
    sketch: skt
    #
    reference: ref
    #
    model: mod
    groom: grm
    effect: efx
    chracter_effect: cfx
    rig: rig
    surface: srf
    #
    camera: cam
    animation: ani
    light: lgt
    light_rig: lgtrig
    #
    plant: plt
    #
    digital_environment: dem
    digital_matte_paint: dmp
    #
    set_dressing: set
    #
    archive: archive
# sequence steps
sequence_steps:
    concept: cpt
    storyboard: stb
    #
    sound: sound
    previs: previs
    #
    edit: edt
    #
    light: lgt
    light_rig: lgtrig
    #
    set_dressing: set
# shot steps
shot_steps:
    concept: cpt
    storyboard: stb
    #
    reference: ref
    #
    sound: sound
    previs: previs
    #
    edit: edt
    #
    camera: cam
    rough_layout: rlo
    animation: ani
    final_layout: flo
    effect: efx
    character_effext: cfx
    light: lgt
    #
    digital_matte_paint: dmp
    compostion: cmp
    #
    set_dressing: set
#
asset_steps_extra: []
#
sequence_steps_extra: []
#
shot_steps_extra: []
# asset
asset-branch-dir: <project-dir>/assets
# step
asset-source-step-dir: <asset-dir>/user/<workspace-name>.<step-name>
asset-user-step-dir: <asset-dir>/user/<workspace-name>.<user_extra-name>
asset-release-step-dir: <asset-dir>/<workspace-name>/<step-name>
asset-temporary-step-dir: <asset-dir>/<workspace-name>/<step-name>
#
asset-step-search-patterns:
    source: '<asset-dir>/user/team.<step-name>/<app-name>/scenes/{any_0}/<asset-name>.<step-name>.{any_1}.{ext}'
    user: '<asset-dir>/user/work.{any_0}/<app-name>/scenes/{any_1}/<asset-name>.<step-name>.{any_2}.{ext}'
    release: <asset-release-step-dir>
# task
asset-source-task-dir: <asset-dir>/user/<workspace-name>.<step-name>
asset-user-task-dir: <asset-dir>/user/<workspace-name>.<user_extra-name>
asset-release-task-dir: <asset-release-step-dir>/<task-name>
asset-temporary-task-dir: <asset-temporary-step-dir>/<task-name>
#
asset-task-search-patterns:
    source: '<asset-dir>/user/team.<step-name>/<app-name>/scenes/{any_0}/<asset-name>.<step-name>.<task-name>.{any_1}.{ext}'
    user: '<asset-dir>/user/work.{any_0}/<app-name>/scenes/{any_1}/<asset-name>.<step-name>.<task-name>.{any_2}.{ext}'
    release: <asset-release-task-dir>
# maya
#   source
asset-source-maya-dir: <asset-source-task-dir>/maya
asset-source-maya-scene-src-dir: <asset-source-maya-dir>/scenes
asset-source-maya-scene-src-file: <asset-source-maya-scene-src-dir>/<task_extra-name>/<asset-version_extra-name>.ma
#
asset-user-maya-dir: <asset-user-task-dir>/maya
asset-user-maya-scene-src-dir: <asset-user-maya-dir>/scenes
asset-user-maya-scene-src-file: <asset-user-maya-scene-src-dir>/<task_extra-name>/<asset-version_extra-name>.ma
# houdini
#   source
asset-source-houdini-dir: <asset-source-task-dir>/houdini
asset-source-houdini-scene-src-dir: <asset-source-houdini-dir>/scenes
asset-source-houdini-scene-src-file: <asset-source-houdini-scene-src-dir>/<task_extra-name>/<asset-version_extra-name>.hip
#   user
asset-user-houdini-dir: <asset-user-task-dir>/houdini
asset-user-houdini-scene-src-dir: <asset-user-houdini-dir>/scenes
asset-user-houdini-scene-src-file: <asset-user-houdini-scene-src-dir>/<task_extra-name>/<asset-version_extra-name>.hip
# katana
#   source
asset-source-katana-dir: <asset-source-task-dir>/katana
asset-source-katana-scene-src-dir: <asset-source-katana-dir>/scenes
asset-source-katana-scene-src-file: <asset-source-katana-scene-src-dir>/<task_extra-name>/<asset-version_extra-name>.katana
#   user
asset-user-katana-dir: <asset-user-task-dir>/katana
asset-user-katana-scene-src-dir: <asset-user-katana-dir>/scenes
asset-user-katana-scene-src-file: <asset-user-katana-scene-src-dir>/<task_extra-name>/<asset-version_extra-name>.katana
# clarisse
#   source
asset-source-clarisse-dir: <asset-source-task-dir>/clarisse
asset-source-clarisse-scene-src-dir: <asset-source-clarisse-dir>/scenes
asset-source-clarisse-scene-src-file: <asset-source-clarisse-scene-src-dir>/<task_extra-name>/<asset-version_extra-name>.project
#   user
asset-user-clarisse-dir: <asset-user-task-dir>/clarisse
asset-user-clarisse-scene-src-dir: <asset-user-clarisse-dir>/scenes
asset-user-clarisse-scene-src-file: <asset-user-clarisse-scene-src-dir>/<task_extra-name>/<asset-version_extra-name>.project
# nuke
#   source
asset-source-nuke-dir: <asset-source-task-dir>/nuke
asset-source-nuke-scene-src-dir: <asset-source-nuke-dir>/scenes
asset-source-nuke-scene-src-file: <asset-source-nuke-scene-src-dir>/<task_extra-name>/<asset-version_extra-name>.nk
#   user
asset-user-nuke-dir: <asset-user-task-dir>/nuke
asset-user-nuke-scene-src-dir: <asset-user-nuke-dir>/scenes
asset-user-nuke-scene-src-file: <asset-user-nuke-scene-src-dir>/<task_extra-name>/<asset-version_extra-name>.nk
# shot =============================================================================================================== #
shot-branch-dir: <project-dir>/sequences
#
shot-source-step-dir: <shot-dir>/user/<workspace-name>.<step-name>
shot-user-step-dir: <shot-dir>/user/<workspace-name>.<user_extra-name>
shot-release-step-dir: <shot-dir>/<workspace-name>/<step-name>
shot-temporary-step-dir: <shot-dir>/<workspace-name>/<step-name>
#
shot-step-search-patterns:
    source: '<shot-dir>/user/team.<step-name>/<app-name>/scenes/{any_0}/<shot-name>.<step-name>.{any_1}.{ext}'
    user: '<shot-dir>/user/work.{any_0}/<app-name>/scenes/{any_1}/<shot-name>.<step-name>.{any_2}.{ext}'
    release: <shot-release-step-dir>
# task
shot-source-task-dir: <shot-dir>/user/<workspace-name>.<step-name>
shot-user-task-dir: <shot-dir>/user/<workspace-name>.<user_extra-name>
shot-release-task-dir: <shot-release-step-dir>/<task-name>
shot-temporary-task-dir: <shot-temporary-step-dir>/<task-name>
#
shot-task-search-patterns:
    source: '<shot-dir>/user/team.<step-name>/<app-name>/scenes/{any_0}/<shot-name>.<step-name>.<task-name>.{any_1}.{ext}'
    user: '<shot-dir>/user/work.{any_0}/<app-name>/scenes/{any_1}/<shot-name>.<step-name>.<task-name>.{any_2}.{ext}'
    release: <shot-release-task-dir>
# maya
#   source
shot-source-maya-dir: <shot-source-task-dir>/maya
shot-source-maya-scene-src-dir: <shot-source-maya-dir>/scenes
shot-source-maya-scene-src-file: <shot-source-maya-scene-src-dir>/<task_extra-name>/<shot-version_extra-name>.ma
#
shot-user-maya-dir: <shot-user-task-dir>/maya
shot-user-maya-scene-src-dir: <shot-user-maya-dir>/scenes
shot-user-maya-scene-src-file: <shot-user-maya-scene-src-dir>/<task_extra-name>/<shot-version_extra-name>.ma
# houdini
#   source
shot-source-houdini-dir: <shot-source-task-dir>/houdini
shot-source-houdini-scene-src-dir: <shot-source-houdini-dir>/scenes
shot-source-houdini-scene-src-file: <shot-source-houdini-scene-src-dir>/<task_extra-name>/<shot-version_extra-name>.hip
#   user
shot-user-houdini-dir: <shot-user-task-dir>/houdini
shot-user-houdini-scene-src-dir: <shot-user-houdini-dir>/scenes
shot-user-houdini-scene-src-file: <shot-user-houdini-scene-src-dir>/<task_extra-name>/<shot-version_extra-name>.hip
# katana
#   source
shot-source-katana-dir: <shot-source-task-dir>/katana
shot-source-katana-scene-src-dir: <shot-source-katana-dir>/scenes
shot-source-katana-scene-src-file: <shot-source-katana-scene-src-dir>/<task_extra-name>/<shot-version_extra-name>.katana
#   user
shot-user-katana-dir: <shot-user-task-dir>/katana
shot-user-katana-scene-src-dir: <shot-user-katana-dir>/scenes
shot-user-katana-scene-src-file: <shot-user-katana-scene-src-dir>/<task_extra-name>/<shot-version_extra-name>.katana
# clarisse
#   source
shot-source-clarisse-dir: <shot-source-task-dir>/clarisse
shot-source-clarisse-scene-src-dir: <shot-source-clarisse-dir>/scenes
shot-source-clarisse-scene-src-file: <shot-source-clarisse-scene-src-dir>/<task_extra-name>/<shot-version_extra-name>.project
#   user
shot-user-clarisse-dir: <shot-user-task-dir>/clarisse
shot-user-clarisse-scene-src-dir: <shot-user-clarisse-dir>/scenes
shot-user-clarisse-scene-src-file: <shot-user-clarisse-scene-src-dir>/<task_extra-name>/<shot-version_extra-name>.project
# nuke
#   source
shot-source-nuke-dir: <shot-source-task-dir>/nuke
shot-source-nuke-scene-src-dir: <shot-source-nuke-dir>/scenes
shot-source-nuke-scene-src-file: <shot-source-nuke-scene-src-dir>/<task_extra-name>/<shot-version_extra-name>.nk
#   user
shot-user-nuke-dir: <shot-user-task-dir>/nuke
shot-user-nuke-scene-src-dir: <shot-user-nuke-dir>/scenes
shot-user-nuke-scene-src-file: <shot-user-nuke-scene-src-dir>/<task_extra-name>/<shot-version_extra-name>.nk
