option:
    platform: ""
    user: ""
    time: ""
    #
    application: ""
    root: ""
    entity: ""
    project: ""
    workspace: ""
    branch: ""
    role: ""
    asset: ""
    step: ""
    task: ""
    version: ""
    #
    sequence: ""
    shot: ""
    #
    asset_batch_name: <option.asset>.<option.step>.<option.task>.<option.version> [<option.time>]
    shot_batch_name: <option.shot>.<option.step>.<option.task>.<option.version> [<option.time>]
    #
    asset_job_name: <option.asset>.<option.step>.<option.task>.<option.version> [<option.time>]
    shot_job_name: <option.shot>.<option.step>.<option.task>.<option.version> [<option.time>]
    #
    job:
        batch_name: ""
        name: ""
        #
        output: ""
        group: "subprogress"
        #
        pool: "subprogress"
        pool2: ""
        command: ""
#
job:
    info:
        Plugin: "Rocket"
        #
        BatchName: <option.job.batch_name>
        Name: <option.job.name>
        #
        Frame: "0"
        Department: <option.step>
        ChunkSize: "1"
        Priority: 50
        Pool: <option.job.pool>
        SecondaryPool: <option.job.pool2>
        #
        Group: <option.job.group>
        #
        Project: <option.project>
        #
        OutputDirectory0: <option.job.output>
        OutputFilename0: ""
        #
        UserName: <option.user>
        MachineLimit: 10
        #
        Comment: ""
        #
        Whitelist: ""
        #
        PreTaskScript: ""
        PostTaskScript: ""
        PreJobScript: ""
        PostJobScript: ""
        #
        OnJobComplete: Nothing
        #
        JobDependencies: ""
        #
        StartupDirectory: <option.job.output>
        #
        ResumeOnoCmpleteDependencies: True
        ResumeOnCompleteDependencies: False
        ResumeOnFailedDependencies: False
        #
        OverrideTaskFailureDetection: True
        FailureDetectionTaskErrors: 2
        #
        ExtraInfo0: <option.platform>
        ExtraInfo1: <option.project>
        ExtraInfo2: <option.workspace>
        ExtraInfo3: <option.entity>
        ExtraInfo4: <option.step>
        ExtraInfo5: <option.task>
        ExtraInfo6: <option.version>
        ExtraInfo7: <option.application>
    plug:
        Arguments: <option.job.command>
        Shell: "default"
        ShellExecute: True
        Executable: ""
        Software: ""
        ErrorCatch: "job-kill"
