method:
    type: ""
    name: ""
    path: ""
    #
    configure: ""
    engine: ""
    script: ""
    #
    tag: ""
    #
    user: ""
    time: ""
    #
    extra:
        platform: ""
        application: '<method.engine>'
        project: '<method.configure>'
    #
    job:
        name: '[<method.configure>][<method.engine>][<method.script>][<method.time>]'
        group_name: '[<method.type>][<method.configure>][<method.engine>]'
        #
        output_directory: ""
        output_file: ""
        #
        group: "subprogress"
        #
        pool: "subprogress"
        pool2: ""
        #
        command: ""
#
job:
    info:
        Plugin: "Rocket"
        #
        BatchName: <method.job.group_name>
        Name: <method.job.name>
        #
        Frame: "0"
        Department: td
        ChunkSize: "1"
        Priority: 50
        Pool: <method.job.pool>
        SecondaryPool: <method.job.pool2>
        #
        Group: <method.job.group>
        #
        Project: <method.configure>
        #
        OutputDirectory0: <method.job.output_directory>
        OutputFilename0: <method.job.output_file>
        #
        UserName: <method.user>
        MachineLimit: 10
        #
        Comment: ""
        #
        Whitelist: ""
        #
        PreTaskScript: ""
        PostTaskScript: ""
        PreJobScript: ""
        PostJobScript: ""
        #
        OnJobComplete: Nothing
        #
        JobDependencies: ""
        #
        StartupDirectory: <method.job.output_directory>
        #
        ResumeOnCompleteDependencies: False
        ResumeOnFailedDependencies: False
        #
        OverrideTaskFailureDetection: True
        FailureDetectionTaskErrors: 2
        #
        ExtraInfo0: <method.extra.platform>
        ExtraInfo1: <method.extra.project>
        ExtraInfo7: <method.extra.application>
    plug:
        Arguments: <method.job.command>
        Shell: "default"
        ShellExecute: True
        Executable: ""
        Software: ""
        ErrorCatch: "job-kill"
