option:
    application: None
    #
    steps:
        model: mod
        surface: srf
        groom: grm
        effect: efx
    #
    tasks:
        model: modeling
        #
        surface: surfacing
        surface-anm: srf_anishading
        surface-cfx: srf_cfxshading
        #
        groom: groom
        effect: effects
#
main:
    directory:
        work-cache-directory:
            keyword: asset-source-cache-dir
            workspace: work

        task-version-directory:
            keyword: asset-release-version-dir
            workspace: publish

        task-no-version-directory:
            keyword: asset-release-no-version-dir
            workspace: publish
    #
    scene:
        maya-file:
            keyword: asset-maya-scene-file
            application: maya
            workspace: publish
        maya-src-file:
            keyword: asset-maya-scene-src-file
            application: maya
            workspace: publish
        work-maya-src-file:
            keyword: asset-source-maya-scene-src-file
            application: maya
        houdini-file:
            keyword: asset-houdini-scene-file
            application: houdini
            workspace: publish
        houdini-src-file:
            keyword: asset-houdini-scene-src-file
            application: houdini
            workspace: publish
        katana-file:
            keyword: asset-katana-scene-file
            application: katana
            workspace: publish
        katana-src-file:
            keyword: asset-katana-scene-src-file
            application: katana
            workspace: publish
        #
        surface-cfx-katana-src-file:
            keyword: asset-katana-scene-src-file
            application: katana
            workspace: publish
            #
            step: <option.steps.surface>
            task: <option.tasks.surface-cfx>
        #
        surface-cfx-maya-src-file:
            keyword: asset-maya-scene-src-file
            application: maya
            workspace: publish
            #
            step: <option.steps.surface>
            task: <option.tasks.surface-cfx>
    #
    render:
        output-dir:
            keyword: asset-render-output-dir
            workspace: publish
        #
        output-render-dir:
            keyword: asset-temporary-katana-render-output-dir
            workspace: publish
        #
        katana-scene-file:
            keyword: asset-render-katana-scene-file
            workspace: publish
        maya-scene-file:
            keyword: asset-render-maya-scene-file
            workspace: publish
        #
        katana-output-dir:
            keyword: asset-render-katana-output-dir
            workspace: publish
    #
    preview:
        mov-file:
            keyword: asset-preview-mov-file
            workspace: publish
    review:
        mov-file:
            keyword: asset-review-file
            workspace: publish
    #
    camera:
        yml-file:
            keyword: asset-camera-persp-yml-file
            workspace: publish
        abc-file:
            keyword: asset-camera-persp-abc-file
            workspace: publish
    #
    deadline:
        job-file:
            keyword: asset-deadline-job-file
            workspace: publish
#
geometries:
    usd:
        model-hi-file:
            keyword: asset-geometry-usd-hi-file
            workspace: publish
            step: <option.steps.model>
            task: <option.tasks.model>
            version: latest
        surface-hi-file:
            keyword: asset-geometry-usd-hi-file
            workspace: publish
            step: <option.steps.surface>
            task: <option.tasks.surface>
            version: latest
        surface-anm-hi-file:
            keyword: asset-geometry-usd-hi-file
            workspace: publish
            step: <option.steps.surface>
            task: <option.tasks.surface-anm>
            version: latest
        surface-cfx-hi-file:
            keyword: asset-geometry-usd-hi-file
            workspace: publish
            step: <option.steps.surface>
            task: <option.tasks.surface-cfx>
            version: latest
        #
        work-surface-hi-file:
            keyword: asset-source-geometry-usd-hi-file
            workspace: work
            step: <option.steps.surface>
            task: <option.tasks.surface>
            version: latest
        #
        hi-file:
            keyword: asset-geometry-usd-hi-file
            workspace: publish
            version: latest
        lo-file:
            keyword: asset-geometry-usd-lo-file
            workspace: publish
            version: latest
        shape-file:
            keyword: asset-geometry-usd-shape-file
            workspace: publish
            version: latest
        temp-file:
            keyword: asset-geometry-usd-temp-file
            workspace: publish
            version: latest
        #
        var-file:
            keyword: asset-geometry-usd-var-file
            workspace: publish
            version: latest
        #
        work-var-file:
            keyword: asset-source-geometry-usd-var-file
            workspace: work
            version: latest
        #
        work-hi-file:
            keyword: asset-source-geometry-usd-hi-file
            workspace: work
            version: latest
        #
        work-lo-file:
            keyword: asset-source-geometry-usd-lo-file
            workspace: work
            version: latest
        #
        work-shape-file:
            keyword: asset-source-geometry-usd-shape-file
            workspace: work
            version: latest
        #
        work-temp-file:
            keyword: asset-source-geometry-usd-temp-file
            workspace: work
            version: latest
        #
        uv_map-file:
            keyword: asset-geometry-uv_map-usd-file
            workspace: publish
            version: latest
        #
        surface-uv_map-file:
            keyword: asset-usd-geometry-uv_map-file
            workspace: publish
            step: <option.steps.surface>
            task: <option.tasks.surface>
            version: latest
    xgen:
        file:
            keyword: asset-geometry-xgen-file
            workspace: publish
            step: <option.steps.groom>
            task: <option.tasks.groom>
            version: latest
        grow-file:
            keyword: asset-geometry-xgen-grow-mesh-file
            workspace: publish
            step: <option.steps.groom>
            task: <option.tasks.groom>
            version: latest
    abc:
        abc-hi-dyn-file:
            keyword: asset-geometry-abc-hi-dyn-file
            workspace: publish
            version: latest
#
looks:
    usd:
        uv_map-file:
            keyword: asset-usd-geometry-uv_map-file
            workspace: publish
            version: latest
        #
        model-uv_map-file:
            keyword: asset-usd-geometry-uv_map-file
            workspace: publish
            step: <option.steps.model>
            task: <option.tasks.model>
            version: latest
        #
        surface-uv_map-file:
            keyword: asset-usd-geometry-uv_map-file
            workspace: publish
            step: <option.steps.surface>
            task: <option.tasks.surface>
            version: latest
        #
        look-file:
            keyword: asset-usd-look-file
            workspace: publish
            version: latest
    ass:
        file:
            keyword: asset-look-ass-file
            workspace: publish
            version: latest
        sub-file:
            keyword: asset-look-ass-sub-file
            workspace: publish
            version: latest
        #
        app-file:
            keyword: asset-look-ass-app-file
            workspace: publish
            version: latest
        app-sub-file:
            keyword: asset-look-ass-app-sub-file
            workspace: publish
            version: latest
        surface-anm-pass-file:
            keyword: asset-look-ass-sub-file
            workspace: publish
            step: <option.steps.surface>
            task: <option.tasks.surface-anm>
            version: latest
        #
        work-file:
            keyword: asset-source-look-ass-file
            workspace: work
            version: latest
        #
        model-file:
            keyword: asset-look-ass-file
            workspace: publish
            step: <option.steps.model>
            task: <option.tasks.model>
            version: latest
        #
        surface-file:
            keyword: asset-look-ass-file
            workspace: publish
            step: <option.steps.surface>
            task: <option.tasks.surface>
            version: latest
        surface-anm-file:
            keyword: asset-look-ass-file
            workspace: publish
            step: <option.steps.surface>
            task: <option.tasks.surface-anm>
            version: latest
    yml:
        file:
            keyword: asset-look-yml-file
            workspace: publish
            version: latest
        surface-anm-file:
            keyword: asset-look-yml-file
            workspace: publish
            step: <option.steps.surface>
            task: <option.tasks.surface-anm>
            version: latest

        #
        work-file:
            keyword: asset-source-look-yml-file
            workspace: work
            version: latest
    klf:
        file:
            keyword: asset-look-klf-file
            workspace: publish
            version: latest
        #
        model-file:
            keyword: asset-look-klf-file
            workspace: publish
            step: <option.steps.model>
            task: <option.tasks.model>
            version: latest
        surface-file:
            keyword: asset-look-klf-file
            workspace: publish
            step: <option.steps.surface>
            task: <option.tasks.surface>
            version: latest
    json:
        file:
            keyword: asset-look-json-file
            workspace: publish
            version: latest
#
textures:
    tx:
        src_dir:
            keyword: asset-texture-src-dir
            workspace: publish
        tgt_dir:
            keyword: asset-texture-tgt-dir
            workspace: publish
        work_dir:
            keyword: asset-source-texture-version-dir
#
usds:
    geometry:
        uv_map-file:
            keyword: asset-usd-geometry-uv_map-file
            workspace: publish
            version: latest
    look:
        file:
            keyword: asset-usd-look-file
            workspace: publish
            version: latest
        #
        properties-file:
            keyword: asset-usd-look-properties-usd-file
            workspace: publish
            version: latest
    payload:
        file:
            keyword: asset-usd-payload-file
            workspace: publish
            version: latest
    registry:
        file:
            keyword: asset-component-registry-usd-file
            workspace: publish
            version: latest
        #
        model-file:
            keyword: asset-component-registry-usd-file
            workspace: publish
            step: <option.steps.model>
            task: <option.tasks.model>
            version: latest
        surface-file:
            keyword: asset-component-registry-usd-file
            workspace: publish
            step: <option.steps.surface>
            task: <option.tasks.surface>
            version: latest
        groom-file:
            keyword: asset-usd-groom-registry-file
            workspace: publish
            step: <option.steps.groom>
            task: <option.tasks.groom>
            version: latest
        effect-file:
            keyword: asset-usd-effect-registry-file
            workspace: publish
            step: <option.steps.groom>
            task: <option.tasks.groom>
            version: latest
