#
elements:
    model__hi:
        layer: model
        keyword: asset-usd-model-hi-file
        workspace: publish
        step: mod
        task: modeling
    #
    hair:
        layer: hair
        keyword: asset-usd-groom-registry-file
        workspace: publish
        step: grm
        task: groom
    #
    effect:
        layer: effect
        keyword: asset-usd-effect-registry-file
        workspace: publish
        step: efx
        task: effects
