menu:
    label: TD-tool(s)
    tools:
        - package_reloader
tool:
    package_reloader:
        label: Reload-package(s)
        chn_label: None
        icon: None
        size:
            - 320
            - 240
        command:
            "import lxutil.dcc.dcc_objects as utl_dcc_objects; reload(utl_dcc_objects);
            p = utl_dcc_objects.PyReloader(
                [
                    'lxscheme', 'lxobj', 'lxresolver',
                    'lxarnold', 'lxar2mtx',
                    'lxutil', 'lxutil_gui', 'lxutil_prd', 'lxutil_fnc',
                    'lxshotgun', 'lxshotgun_fnc',
                    'lxshotgun_gui',
                    'lxkatana'
                ]
            );
            p.set_reload()"