menu:
    label: TD-tool(s)
    tools:
        - package_reloader
tool:
    package_reloader:
        label: Reload-package(s)
        chn_label: None
        icon: None
        size:
            - 320
            - 240
        command: ''